sudo: false
language: elixir

matrix:
  include:
    - os: linux
      otp_release: 19.0
      elixir: 1.3.0
    - os: linux
      otp_release: 19.0
      elixir: 1.4.0
    - os: linux
      otp_release: 20.0
      elixir: 1.5.0
    - os: linux
      otp_release: 20.0
      elixir: 1.6.0
